version: '3.9'

services:

  wordpress:
    image: wordpress
    restart: always
    container_name: wordpress-prod-1
    hostname: elikesbikes.com
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db-prod-1
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    networks:
      frontend:
    volumes:
     - wordpress:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.wordpress-prod-1.loadbalancer.server.port=80"
      - "traefik.http.services.wordpress-prod-1.loadbalancer.server.scheme=http"
      - "traefik.http.routers.wordpress-prod-1-http.entrypoints=web"
      - "traefik.http.routers.wordpress-prod-1-http.rule=Host(`elikesbikes.com`,`emilikesbikes.home.elikesbikes.cloud`)"
      - "traefik.http.routers.wordpress-prod-1-https.entrypoints=websecure"
      - "traefik.http.routers.wordpress-prod-1-https.rule=Host(`elikesbikes.com`,`emilikesbikes.home.elikesbikes.cloud`)"
      - "traefik.http.routers.wordpress-prod-1-https.tls=true"
      - "traefik.http.routers.wordpress-prod-1-https.tls.certresolver=production"
      - "traefik.http.routers.wordpress-prod-1-https.tls.domains[1].main=emilikesbikes.home.elikesbikes.cloud"
      - "traefik.http.routers.wordpress-prod-1-https.tls.domains[0].main=elikesbikes.com"


  db:
    image: mysql:8.0
    hostname : db-prod-1
    restart: always
    container_name: db-prod-1
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    networks:
      frontend: 

volumes:
  wordpress:
  db:

networks:
  frontend:
    external: true


