version: "3.8"
networks:
  frontend:
    external: true
services:
  portainer:
    container_name: portainer-prod-4
    image: portainer/portainer-ce:latest
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.portainer-prod-4.loadbalancer.server.port=9000"
      - "traefik.http.services.portainer-prod-4.loadbalancer.server.scheme=http"
      
      - "traefik.http.routers.portainer-prod-4-http.entrypoints=web"
      - "traefik.http.routers.portainer-prod-4-http.rule=Host(`ddocker-prod-4.home.elikesbikes.cloud`)"      
      
      - "traefik.http.routers.portainer-prod-4-https.rule=Host(`docker-prod-4.home.elikesbikes.cloud`)"
      - "traefik.http.routers.portainer-prod-4-https.entrypoints=websecure"
      
      - "traefik.http.routers.portainer-prod-4-https.tls=true"
      - "traefik.http.routers.portainer-prod-4-https.tls.certresolver=production"                                                                    
      - "traefik.http.routers.portainer-prod-4-https.tls.domains[0].main=docker-prod-4.home.elikesbikes.cloud"

    networks:
      frontend:
volumes:
  portainer_data:
    driver: local
