networks:
  frontend:
    external: true
services:
  portainer:
    container_name: portainer-prod-4
    image: portainer/portainer-ce:latest
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`docker.home.elikesbikes.com`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=production"
      - "traefik.http.routers.portainer.middlewares=security-headers@file"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      frontend:
volumes:
  portainer_data:
    driver: local
