networks:
  frontend:
    external: true

services:
  syslog_mongo:
    image: mongo:7.0
    container_name: syslog_mongodb
    hostname: mongodb
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ./mongo_data:/data/db
    networks:
      - frontend

  syslog_opensearch:
    image: opensearchproject/opensearch:2.19.0
    container_name: syslog_opensearch
    hostname: opensearch
    environment:
      - TZ=${TZ}
      - "OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS}"
      - "bootstrap.memory_lock=${OPENSEARCH_BOOTSTRAP_MEMORY_LOCK}"
      - "discovery.type=${OPENSEARCH_DISCOVERY_TYPE}"
      - "action.auto_create_index=${OPENSEARCH_ACTION_AUTO_CREATE_INDEX}"
      - "DISABLE_SECURITY_PLUGIN=${OPENSEARCH_DISABLE_SECURITY_PLUGIN}"
    ports:
      - 9200:9200/tcp  
    networks:
      - frontend      

  syslog_graylog:
    image: graylog/graylog:7.0
    container_name: syslog_graylog
    hostname: graylog
    user: "1100:1100"
    depends_on:
      - syslog_opensearch
      - syslog_mongo
    environment:
      - TZ=${TZ}
      - GRAYLOG_HTTP_BIND_ADDRESS=${GRAYLOG_HTTP_BIND_ADDRESS}
      - GRAYLOG_HTTP_EXTERNAL_URI=${GRAYLOG_HTTP_EXTERNAL_URI}
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
      - GRAYLOG_ROOT_USERNAME=${GRAYLOG_ROOT_USERNAME}
      - GRAYLOG_ROOT_TIMEZONE=${GRAYLOG_ROOT_TIMEZONE}
      - GRAYLOG_MONGODB_URI=${GRAYLOG_MONGODB_URI}
      - GRAYLOG_OPENSEARCH_HOSTS=${GRAYLOG_OPENSEARCH_HOSTS}
      - GRAYLOG_ELASTICSEARCH_HOSTS=${GRAYLOG_ELASTICSEARCH_HOSTS}
      - GRAYLOG_DATA_DIR=${GRAYLOG_DATA_DIR}
      - GRAYLOG_NODE_ID_FILE=${GRAYLOG_NODE_ID_FILE}
    volumes:
      - ./graylog_data:/usr/share/graylog/data
    networks:
      - frontend
    restart: always
    ports:
      - "1514:1514/tcp"   # Syslog TCP
      - "1514:1514/udp"   # Syslog UDP
      - "514:514/tcp"     # Standard Syslog TCP
      - "514:514/udp"     # Standard Syslog UDP
      - "1515:1515/udp"   # Custom Input
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.graylog.rule=Host(`graylog-tars.home.elikesbikes.com`)"
      - "traefik.http.routers.graylog.entrypoints=websecure"
      - "traefik.http.routers.graylog.tls.certresolver=production"
      - "traefik.http.routers.graylog.middlewares=security-headers@file"
      - "traefik.http.services.graylog.loadbalancer.server.port=9000"