version: '2'
services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge-prod-1
    restart: always    
    network_mode: "host"  
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"


networks:
  frontend:
    external: true